[build]
  publish = "."
  functions = "netlify/functions"

[[edge_functions]]
  function = "upload-share-file"
  path = "/api/upload-file"

[[edge_functions]]
  function = "get-shared-file"
  path = "/api/shared-file"
